[package]
name = "git-ls"
version = "0.1.0"
authors = ["linkviii <LinkEighth@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.13"
lscolors = "0.7"
pathdiff = "0.2"